version: "3.9"

services:
  my_pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PORT: 5432
      HOST: localhost

    volumes:
      - ./db_avito:/var/lib/postgresql/data

