# Generated by Django 4.1.2 on 2022-10-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_selectionad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectionad',
            old_name='ads',
            new_name='items',
        ),
    ]
