# Generated by Django 4.1.2 on 2022-10-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_ads_selectionad_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectionad',
            options={'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
    ]
