# Generated by Django 4.1.2 on 2022-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_selectionad_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionad',
            name='items',
            field=models.ManyToManyField(to='ads.ad'),
        ),
    ]
